# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings - see https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20

# Environment Properties
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.11
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.11]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.11.45

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=practical_additions
# The human-readable display name for the mod.
mod_name=Practical Additions
# The license of the mod. Review your options at https://choosealicense.com/.
mod_license=All Rights Reserved
# The mod version. See https://semver.org/
mod_version=1.0.0
# The group ID for the mod. Should match the base package used for the mod sources.
mod_group_id=com.danako.practical_additions
